### ISSUE TITLE
Plugin cannot be loaded in Grafana 6.4.1

### ISSUE THREAD

**Issue by aemaem** [grafana/influxdb-flux-datasource#48] opened 2019-10-02 15:52 UTC
Hi, when adding a new datasource, I get the following error message on the Grafana UI:

Error: Unexpected token '<' Evaluating http://localhost/public/slate-react Loading plugins/grafana-influxdb-flux-datasource/module

Grafana Version 6.4.1

**Comment by briangann** [comment] 2019-10-04 05:03
the change to slate in Grafana v6.4 has broken compatibility with this plugin.

**Comment by andig** [comment] 2019-10-04 14:24
Problem confirmed. Influx datasource is broken on Grafana 6.4.

**Comment by lephisto** [comment] 2019-10-07 17:59
So sad, already using Flux in Production.

**Comment by briangann** [comment] 2019-10-11 04:29
this will be released 10/11, in the last phase of testing

**Comment by briangann** [comment] 2019-10-11 14:18
v5.4.0 is out

**Closed by briangann** 2019-10-11 14:18 UTC
Labels: bug

**Comment by teodoryantcheff** [comment] 2019-10-17 13:58
Same behavior on 6.4.2.

`Error: Unexpected token '<' Evaluating https://xxxxxx/public/slate-react Loading plugins/grafana-influxdb-flux-datasource/module
`

**Comment by lephisto** [comment] 2019-10-17 15:19
@teodoryantcheff Did you update Plugins as well? flux datasource works for me @6.4.2 with updates plugins:

```grafana-cli plugins update-all```

**Comment by teodoryantcheff** [comment] 2019-10-18 07:07
@lephisto `plugins update all` did resolve it. Thanks !

**Comment by aniketdey** [comment] 2020-12-10 15:49
I am trying to add a AppDynamics data source forked from original plugin. The url is https://github.com/oberschlauberger/appdynamics-grafana-datasource . I am using Grafana v7.3.5 and getting same error while adding the data source. Please suggest way to rectify this.
<img width="830" alt="errorgrafana" src="https://user-images.githubusercontent.com/50565861/101794905-5aed4b80-3b2d-11eb-99e9-57f3bcc89645.PNG">
