### ISSUE TITLE
InfluxDB 1.8 does no longer work since updating to grafana and plugin to 7.0

### ISSUE THREAD

**Issue by disaster123** [grafana/influxdb-flux-datasource#101] opened 2020-05-20 10:38 UTC
While using this with Grafana 6 worked fine. It stopped working with Grafana 7 and plugin version 7.

Setting up the plugin now always fails with:
```
500 Internal Server Error: {"error":"panic: column retentionPeriod:int is not of type string"}
```

**Comment by lephisto** [comment] 2020-05-20 12:34
Got the same issue, can't connect to the flux endpoint of a v1.x Influxdb.

**Comment by ryantxu** [comment] 2020-05-20 14:16
Which version of influx?  This is expected to work with 1.8+ and 2.0
https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility

**Comment by disaster123** [comment] 2020-05-20 14:26
Influx 1.8.0 here old plugin version works fine even with Grafana 7

**Comment by dsantaolalla** [comment] 2020-05-20 15:05
I have the same problem, 

`500 Internal Server Error: {"error":"panic: column retentionPeriod:int is not of type string"}`

My versions are:

Grafana 7.0.0
Influxdb 1.8.0
influxdb-flux-datasource plugin 7.0.0

**Comment by agolovenko** [comment] 2020-05-21 18:17
same here

**Comment by germm** [comment] 2020-05-23 07:06
i have the same problem

**Comment by jesjimher** [comment] 2020-05-25 10:43
Same problem, flux doesn't work since update to v7, giving the same error.

**Comment by ext452** [comment] 2020-05-26 08:41
same problem :(
grafana 7.0
influxdb 1.8.0
influxdb-flux-datasource plugin 7.0.0

**Comment by easthy-alterpost** [comment] 2020-05-26 11:07
The same problem:
influxdb-1.8.0.x86_64
grafana-7.0.0-1.x86_64
Flux (InfluxDB) [BETA] v.7.0.0

**Comment by andig** [comment] 2020-05-31 07:45
Looks like another duplicate of #100

**Comment by andig** [comment] 2020-05-31 09:18
Sorry for the confusion. Same problem with #105 

Working:
Grafana 6.4
Flux 5.4.1

Broken:
Grafana 7.0
Flux 7.0

Both running against InfluxDB 1.8.4

**Comment by andig** [comment] 2020-06-02 11:54
I'm seeing this in the influxdb (v1.8.4) logfile:

```
[httpd] 172.22.0.1 - - [02/Jun/2020:11:46:29 +0000] "GET /health HTTP/1.1" 200 106 "-" "influxdb-client-go/1.1.0  (linux; amd64)" b284b207-a4c6-11ea-859b-0242ac160002 21098
ts=2020-06-02T11:46:29.696143Z lvl=info msg="Execute source panic" log_id=0N0wkt60000 error="panic: column retentionPeriod:int is not of type string"
```

**Comment by andig** [comment] 2020-06-02 12:16
The actual error message is in https://github.com/influxdata/influxdb/blob/1.8/patches/flux.patch#L1816 and has since been removed.

/cc @jsternberg who has upgraded flux in https://github.com/influxdata/influxdb/commit/636a27e77f00f0faeff186c8b6b005d79da7c424

**Comment by scurvy-dog** [comment] 2020-06-05 17:47
Encountered the same error today when setting up a Flux datasource today. Datasource works fine in Chronograf with specifying the influx host with no authentication.

Grafana 7.0.1
Influx 1.8
Flux 7.0

**Comment by andig** [comment] 2020-06-13 10:10
ping @jsternberg- this is still an issue:

<img width="700" alt="Screenshot 2020-06-13 at 12 09 02" src="https://user-images.githubusercontent.com/184815/84566094-d2a11000-ad6e-11ea-90ff-67871c083d08.png">

**Comment by korre73** [comment] 2020-06-15 17:09
Same Problem on 

Grafana 7.0.3
Influx 1.8.0
Flux 7.0


[[https://github.com/grafana/influxdb-flux-datasource/issues/101#issuecomment-631507749]](Old Version means Flux 5.4.1 ???)
How can i downgrade to this version????

**Comment by dsantaolalla** [comment] 2020-06-16 08:00
@korre73 you can downgrade with running the following where your grafana is running:

Uninstall first:
$ grafana-cli plugins install grafana-influxdb-flux-datasource

Then install the specific version 5.4.1
$ grafana-cli plugins install grafana-influxdb-flux-datasource 5.4.1

**Comment by jesjimher** [comment] 2020-06-16 08:04
But will old version work with Grafana 7? Plugin documentation seems to state that latest works with Grafana 7, and 5.4.1 works with Grafana 6.

**Comment by disaster123** [comment] 2020-06-16 08:08
Yes it does i'm stil using 5.4.1 since weeks with grafana 7

**Comment by andig** [comment] 2020-06-29 16:41
I have given up on waiting for feedback and reverted to grafana 6.7.4 as 7.0.4 has become totally useless for me.

**Comment by lephisto** [comment] 2020-07-16 22:15
Still not working with Grafana 7.1... are there any intentions to get Flux working again? I'm stuck with 6.7.4 on projects that require fluxlang..

**Comment by dswarbrick** [comment] 2020-07-16 22:20
@lephisto Grafana 7.1 has support for Flux built-in. This plugin is essentially obsolete now (for users of Grafana 7.1+).

When setting up an InfluxDB data source, you now have the option to specify InfluxQL or Flux query language.

**Comment by CharlesGodwin** [comment] 2020-07-16 22:35
@dswarbrick can you send me a creen shot of the config for a FLUX and influxdb 1.8 setup. I can't get mine to work. thanks

an example URL, organiziation (how do I get that?) and Token

**Comment by ryantxu** [comment] 2020-07-16 22:36
Check:
https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/

it looks like you need an empty org

**Comment by dswarbrick** [comment] 2020-07-16 22:39
@CharlesGodwin The organization can be whatever - ACME Widgets, Inc., if you like.

The token is simply the concatenation of the InfluxDB 1.8 username and password, with a colon between, e.g. `grafana:secretpw`

**Comment by CharlesGodwin** [comment] 2020-07-16 22:54
Of course, that was intuitively obvious.

**Comment by timhallinflux** [comment] 2020-07-17 05:40
Now that Grafana 7.1 is out, the updated InfluxDB data source is much more straightforward to use and there is supporting documentation on the Grafana site and InfluxDB site as well. Let us know if there are still outstanding issues.

**Comment by andig** [comment] 2020-07-17 12:53
> Let us know if there are still outstanding issues.

@timhallinflux using 7.1 against Influx 1.8 datasource definition fails unless you define an organisation. Its also not obvious you need to define token as user:password. Both are without useful error message in the ui.

**Comment by jesjimher** [comment] 2020-07-17 13:39
> @timhallinflux using 7.1 against Influx 1.8 datasource definition fails unless you define an organisation. Its also not obvious you need to define token as user:password. Both are without useful error message in the ui.

In my case, it works just entering a random text as an organisation. Token may be left blank too, once you click Save/test it gets filled automatically.

**Comment by ryantxu** [comment] 2020-07-17 16:14
See https://github.com/grafana/grafana/issues/26397

random text in the org will work.  We will improve that soon

**Closed by ryantxu** 2020-07-17 16:14 UTC
